# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nikhil/Documents/Code/CS360/MAPF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nikhil/Documents/Code/CS360/MAPF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.21.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nikhil/Documents/Code/CS360/MAPF/CMakeFiles /Users/nikhil/Documents/Code/CS360/MAPF/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nikhil/Documents/Code/CS360/MAPF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MAPF

# Build rule for target.
MAPF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MAPF
.PHONY : MAPF

# fast build rule for target.
MAPF/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/build
.PHONY : MAPF/fast

#=============================================================================
# Target rules for targets named Google_Tests_run

# Build rule for target.
Google_Tests_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Google_Tests_run
.PHONY : Google_Tests_run

# fast build rule for target.
Google_Tests_run/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/CMakeFiles/Google_Tests_run.dir/build.make Google_tests/CMakeFiles/Google_Tests_run.dir/build
.PHONY : Google_Tests_run/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googlemock/CMakeFiles/gmock.dir/build.make Google_tests/lib/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googlemock/CMakeFiles/gmock_main.dir/build.make Google_tests/lib/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googletest/CMakeFiles/gtest_main.dir/build.make Google_tests/lib/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googletest/CMakeFiles/gtest.dir/build.make Google_tests/lib/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

AStarPlanner.o: AStarPlanner.cpp.o

.PHONY : AStarPlanner.o

# target to build an object file
AStarPlanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/AStarPlanner.cpp.o
.PHONY : AStarPlanner.cpp.o

AStarPlanner.i: AStarPlanner.cpp.i

.PHONY : AStarPlanner.i

# target to preprocess a source file
AStarPlanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/AStarPlanner.cpp.i
.PHONY : AStarPlanner.cpp.i

AStarPlanner.s: AStarPlanner.cpp.s

.PHONY : AStarPlanner.s

# target to generate assembly for a file
AStarPlanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/AStarPlanner.cpp.s
.PHONY : AStarPlanner.cpp.s

CBS.o: CBS.cpp.o

.PHONY : CBS.o

# target to build an object file
CBS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/CBS.cpp.o
.PHONY : CBS.cpp.o

CBS.i: CBS.cpp.i

.PHONY : CBS.i

# target to preprocess a source file
CBS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/CBS.cpp.i
.PHONY : CBS.cpp.i

CBS.s: CBS.cpp.s

.PHONY : CBS.s

# target to generate assembly for a file
CBS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/CBS.cpp.s
.PHONY : CBS.cpp.s

Google_tests/test1.o: Google_tests/test1.cpp.o

.PHONY : Google_tests/test1.o

# target to build an object file
Google_tests/test1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/Google_tests/test1.cpp.o
.PHONY : Google_tests/test1.cpp.o

Google_tests/test1.i: Google_tests/test1.cpp.i

.PHONY : Google_tests/test1.i

# target to preprocess a source file
Google_tests/test1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/Google_tests/test1.cpp.i
.PHONY : Google_tests/test1.cpp.i

Google_tests/test1.s: Google_tests/test1.cpp.s

.PHONY : Google_tests/test1.s

# target to generate assembly for a file
Google_tests/test1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/Google_tests/test1.cpp.s
.PHONY : Google_tests/test1.cpp.s

MAPFInstance.o: MAPFInstance.cpp.o

.PHONY : MAPFInstance.o

# target to build an object file
MAPFInstance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/MAPFInstance.cpp.o
.PHONY : MAPFInstance.cpp.o

MAPFInstance.i: MAPFInstance.cpp.i

.PHONY : MAPFInstance.i

# target to preprocess a source file
MAPFInstance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/MAPFInstance.cpp.i
.PHONY : MAPFInstance.cpp.i

MAPFInstance.s: MAPFInstance.cpp.s

.PHONY : MAPFInstance.s

# target to generate assembly for a file
MAPFInstance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/MAPFInstance.cpp.s
.PHONY : MAPFInstance.cpp.s

PrioritizedSearch.o: PrioritizedSearch.cpp.o

.PHONY : PrioritizedSearch.o

# target to build an object file
PrioritizedSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/PrioritizedSearch.cpp.o
.PHONY : PrioritizedSearch.cpp.o

PrioritizedSearch.i: PrioritizedSearch.cpp.i

.PHONY : PrioritizedSearch.i

# target to preprocess a source file
PrioritizedSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/PrioritizedSearch.cpp.i
.PHONY : PrioritizedSearch.cpp.i

PrioritizedSearch.s: PrioritizedSearch.cpp.s

.PHONY : PrioritizedSearch.s

# target to generate assembly for a file
PrioritizedSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/PrioritizedSearch.cpp.s
.PHONY : PrioritizedSearch.cpp.s

task0/task0.o: task0/task0.cpp.o

.PHONY : task0/task0.o

# target to build an object file
task0/task0.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task0/task0.cpp.o
.PHONY : task0/task0.cpp.o

task0/task0.i: task0/task0.cpp.i

.PHONY : task0/task0.i

# target to preprocess a source file
task0/task0.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task0/task0.cpp.i
.PHONY : task0/task0.cpp.i

task0/task0.s: task0/task0.cpp.s

.PHONY : task0/task0.s

# target to generate assembly for a file
task0/task0.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task0/task0.cpp.s
.PHONY : task0/task0.cpp.s

task1/task1.o: task1/task1.cpp.o

.PHONY : task1/task1.o

# target to build an object file
task1/task1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task1/task1.cpp.o
.PHONY : task1/task1.cpp.o

task1/task1.i: task1/task1.cpp.i

.PHONY : task1/task1.i

# target to preprocess a source file
task1/task1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task1/task1.cpp.i
.PHONY : task1/task1.cpp.i

task1/task1.s: task1/task1.cpp.s

.PHONY : task1/task1.s

# target to generate assembly for a file
task1/task1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task1/task1.cpp.s
.PHONY : task1/task1.cpp.s

task2/task2.o: task2/task2.cpp.o

.PHONY : task2/task2.o

# target to build an object file
task2/task2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task2/task2.cpp.o
.PHONY : task2/task2.cpp.o

task2/task2.i: task2/task2.cpp.i

.PHONY : task2/task2.i

# target to preprocess a source file
task2/task2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task2/task2.cpp.i
.PHONY : task2/task2.cpp.i

task2/task2.s: task2/task2.cpp.s

.PHONY : task2/task2.s

# target to generate assembly for a file
task2/task2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task2/task2.cpp.s
.PHONY : task2/task2.cpp.s

task3/task3.o: task3/task3.cpp.o

.PHONY : task3/task3.o

# target to build an object file
task3/task3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task3/task3.cpp.o
.PHONY : task3/task3.cpp.o

task3/task3.i: task3/task3.cpp.i

.PHONY : task3/task3.i

# target to preprocess a source file
task3/task3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task3/task3.cpp.i
.PHONY : task3/task3.cpp.i

task3/task3.s: task3/task3.cpp.s

.PHONY : task3/task3.s

# target to generate assembly for a file
task3/task3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAPF.dir/build.make CMakeFiles/MAPF.dir/task3/task3.cpp.s
.PHONY : task3/task3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Google_Tests_run"
	@echo "... MAPF"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... AStarPlanner.o"
	@echo "... AStarPlanner.i"
	@echo "... AStarPlanner.s"
	@echo "... CBS.o"
	@echo "... CBS.i"
	@echo "... CBS.s"
	@echo "... Google_tests/test1.o"
	@echo "... Google_tests/test1.i"
	@echo "... Google_tests/test1.s"
	@echo "... MAPFInstance.o"
	@echo "... MAPFInstance.i"
	@echo "... MAPFInstance.s"
	@echo "... PrioritizedSearch.o"
	@echo "... PrioritizedSearch.i"
	@echo "... PrioritizedSearch.s"
	@echo "... task0/task0.o"
	@echo "... task0/task0.i"
	@echo "... task0/task0.s"
	@echo "... task1/task1.o"
	@echo "... task1/task1.i"
	@echo "... task1/task1.s"
	@echo "... task2/task2.o"
	@echo "... task2/task2.i"
	@echo "... task2/task2.s"
	@echo "... task3/task3.o"
	@echo "... task3/task3.i"
	@echo "... task3/task3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

